/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tr.com.bites.poc.documentparser.gui;

import javax.swing.JButton;
import tr.com.bites.poc.documentparser.document.TempDocument;

/**
 *
 * @author fatihs
 */
public class TempFileInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form FileInfoPanel
     */
    public TempFileInfoPanel() {
        initComponents();
        
    }
    
    public void setTempFile(TempDocument document){
        this.lblPathValue .setText(document.getAbsolutePath());
    }
    
    public JButton getBtnOpenTempFile() {
        return btnOpenTempFile;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFilePath = new javax.swing.JLabel();
        lblPathValue = new javax.swing.JLabel();
        btnOpenTempFile = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblFilePath.setText("File Path : ");
        jPanel1.add(lblFilePath, java.awt.BorderLayout.WEST);

        lblPathValue.setText("...");
        jPanel1.add(lblPathValue, java.awt.BorderLayout.CENTER);

        btnOpenTempFile.setText("Open Temp File");
        jPanel1.add(btnOpenTempFile, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenTempFile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFilePath;
    private javax.swing.JLabel lblPathValue;
    // End of variables declaration//GEN-END:variables
}
